// Generated by CoffeeScript 1.7.1
(function() {
  var modelsObj, models_array, models_dir, mongoose, tools, _;

  _ = require('lodash');

  mongoose = require('mongoose');

  tools = require('./tools');

  models_dir = __dirname + '/models';

  models_array = tools.loadModules(models_dir);

  modelsObj = {};

  module.exports = {
    init: function(host, name) {
      var mongo_uri;
      mongo_uri = 'mongodb://' + host + '/' + name;
      return mongoose.connect(mongo_uri);
    },
    status: function() {
      var status;
      status = {
        state: 'not ready'
      };
      if (mongoose.connection.readyState === 1) {
        status.state = 'ready';
      }
      return status;
    },
    models: function() {
      if (_.isEmpty(modelsObj)) {
        _.each(models_array, function(model, index) {
          return modelsObj[index] = mongoose.model(index, mongoose.Schema(model.model));
        });
        return modelsObj;
      }
      return modelsObj;
    }
  };

}).call(this);
