// Generated by CoffeeScript 1.7.1
(function() {
  var appLogger, bunyan, dotenv, env, restify, routes, server, tools;

  dotenv = require('dotenv');

  restify = require('restify');

  bunyan = require('bunyan');

  routes = require('./routes');

  tools = require('./tools');

  dotenv.load();

  env = {
    app_host: process.env.app_host || '0.0.0.0',
    app_port: parseInt(process.env.app_port || 3000),
    app_name: process.env.app_name,
    db_host: process.env.db_host || 'localhost',
    db_name: process.env.db_name,
    db_port: parseInt(process.env.db_port || 27017)
  };

  appLogger = bunyan.createLogger({
    name: env.name + ' app server',
    level: process.env.LOG_LEVEL || 'warn',
    stream: process.stdout,
    serializers: bunyan.stdSerializers
  });

  server = restify.createServer({
    name: process.env.name
  });

  server.pre(restify.pre.sanitizePath());

  server.use(restify.acceptParser(server.acceptable));

  server.use(restify.queryParser());

  server.use(restify.bodyParser());

  server.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type");
    res.header("Access-Control-Allow-Methods", "POST, GET, PUT, DELETE, OPTIONS");
    return next();
  });

  server.use(restify.fullResponse());

  server.on('after', restify.auditLogger({
    log: appLogger
  }));

  routes(server, env.db_host, env.db_name, env.db_port);

  server.listen(env.app_port, env.app_host, function() {
    if (process.env['NODE_ENV'] !== 'production') {
      return console.log('%s listening at %s', server.name, server.url);
    }
  });

  module.exports = function() {
    return server;
  };

}).call(this);
