// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(server, db) {
    server.get('/api/audiences/cookies', function(req, res, next) {
      return db.Cookie.find(function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = {};
        rslts['count'] = rcrds.length;
        rslts['segments'] = rcrds;
        res.send(rslts);
        return next();
      });
    });
    return server.get('/api/audiences/segments', function(req, res, next) {
      return db.Segment.find(function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = {};
        rslts['count'] = rcrds.length;
        rslts['segments'] = rcrds;
        res.send(rslts);
        return next();
      });
    });
  };

}).call(this);
