// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(server, db) {
    server.get('/api/media/business_days', function(req, res, next) {
      return db.Business_day.find(function(err, rslts) {
        if (err) {
          return err;
        }
        return res.send(rslts);
      });
    });
    server.get('/api/media/business_days/year/:year', function(req, res, next) {
      return db.Business_day.find({
        year: req.params.year
      }, function(err, rslts) {
        if (err) {
          return err;
        }
        return res.send(rslts);
      });
    });
    server.get('/api/media/business_days/year/:year/month/:month', function(req, res, next) {
      return db.Business_day.find({
        year: req.params.year,
        month: req.params.month
      }, function(err, rslts) {
        if (err) {
          return err;
        }
        return res.send(rslts);
      });
    });
    server.get('/api/media/business_days/month/:month', function(req, res, next) {
      return db.Business_day.find({
        month: req.params.month
      }, function(err, rslts) {
        if (err) {
          return err;
        }
        return res.send(rslts);
      });
    });
    server.get('/api/media/business_days/holidays', function(req, res, next) {
      return db.Business_day.where('holidays').exists().exec(function(err, rslts) {
        if (err) {
          return err;
        }
        return res.send(rslts);
      });
    });
    return server.get('/api/media/business_days/holidays/year/:year', function(req, res, next) {
      return db.Business_day.find({
        year: req.params.year
      }).where('holidays').exists().exec(function(err, rslts) {
        if (err) {
          return err;
        }
        return res.send(rslts);
      });
    });
  };

}).call(this);
