// Generated by CoffeeScript 1.7.1
(function() {
  var audiences, business_days, dataStore, media;

  dataStore = require('../ds');

  business_days = require('./business_days');

  media = require('./media');

  audiences = require('./audiences');

  module.exports = function(server, db_host, db_name, db_port) {
    var db;
    dataStore.init(db_host, db_name, db_port);
    db = dataStore.models();
    business_days(server, db);
    media(server, db);
    audiences(server, db);
    server.get('/hello/:name', function(req, res, next) {
      res.send({
        hello: req.params.name,
        date: new Date
      });
      return next();
    });
    return server.get('/', function(req, res, next) {
      var resObj;
      resObj = {
        sever: process.env.app_name,
        remote: req.connection.remoteAddress,
        date: new Date,
        msg: 'for more info, try @alvaromuir'
      };
      res.send(resObj);
      return next();
    });
  };

}).call(this);
