// Generated by CoffeeScript 1.7.1
(function() {
  var rsltsObj, _;

  _ = require('lodash');

  rsltsObj = function(rcrds, category, criteria) {
    var doc, rcrd, rslts, _i, _len;
    rslts = {};
    rslts[category] = criteria;
    rslts['placement count'] = rcrds.length;
    rslts['MediaCostM'] = 0;
    rslts['ImpsM'] = 0;
    rslts['ClicksM'] = 0;
    rslts['Consumer - Homepage : Learn_Shop_Unique: Click-through Conversions'] = 0;
    rslts['Consumer - Homepage : Learn_Shop_Unique: View-through Conversions'] = 0;
    rslts['Consumer - Remarketing : Loop Qual Success_FiOS TV: Click-through Conversions'] = 0;
    rslts['Consumer - Remarketing : Loop Qual Success_FiOS TV: View-through Conversions'] = 0;
    rslts['Consumer - Remarketing : Loop Qual Success_FiOS Internet: Click-through Conversions'] = 0;
    rslts['Consumer - Remarketing : Loop Qual Success_FiOS Internet: View-through Conversions'] = 0;
    rslts['Consumer - Remarketing : Loop Qual Success_CHSI: Click-through Conversions'] = 0;
    rslts['Consumer - Remarketing : Loop Qual Success_CHSI: View-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO CHSI Order - AM: Click-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO CHSI Order - AM: View-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO CHSI Order - NC: Click-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO CHSI Order - NC: View-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS Internet Order - AM: Click-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS Internet Order - AM: View-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS Internet Order - NC: Click-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS Internet Order - NC: View-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS TV Order - AM: Click-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS TV Order - AM: View-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS TV Order - NC: Click-through Conversions'] = 0;
    rslts['Consumer - Order Confirmation : GO FiOS TV Order - NC: View-through Conversions'] = 0;
    rslts['Consumer - Homepage : VPM_2013: Click-through Conversions'] = 0;
    rslts['Consumer - Homepage : VPM_2013: View-through Conversions'] = 0;
    rslts['GoodVisitsM'] = 0;
    rslts['CTGoodVisitsM'] = 0;
    rslts['TVLQSm'] = 0;
    rslts['CTTVLQSm'] = 0;
    rslts['Total LQS'] = 0;
    rslts['TVOrdersM'] = 0;
    rslts['CTTVOrdersM'] = 0;
    rslts['Internet Orders'] = 0;
    rslts['CHSI Orders'] = 0;
    rslts['Total Orders'] = 0;
    rslts['Total VisitsM'] = 0;
    for (_i = 0, _len = rcrds.length; _i < _len; _i++) {
      rcrd = rcrds[_i];
      doc = rcrd._doc;
      _.forIn(doc, function(val, key) {
        if (!isNaN(doc[key])) {
          return rslts[key] += parseInt(doc[key]);
        }
      });
    }
    rslts['placements'] = rcrds;
    return rslts;
  };

  module.exports = function(server, db) {
    server.get('/api/media/placements/', function(req, res, next) {
      return db.Media.find(function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = _.without(rslts, '');
        rslts = rsltsObj(rcrds, 'placement', 'all');
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/placements/id/:id', function(req, res, next) {
      return db.Media.findById(req.params.id, function(err, doc) {
        if (err) {
          return err;
        }
        if (doc) {
          res.send(doc);
          return next();
        } else {
          res.send({
            error: 'record with id ' + req.params.id + ' not found'
          });
          return next();
        }
      });
    });
    server.get('/api/media/placements/:placement', function(req, res, next) {
      return db.Media.find({
        'Placement': req.params.placement
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'placement', req.params.placement);
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/campaigns', function(req, res, next) {
      return db.Media.distinct('Campaign', function(err, rslts) {
        var count;
        if (err) {
          return err;
        }
        rslts = _.without(rslts, '');
        count = rslts.length;
        res.send({
          'total campaigns': count,
          campaigns: rslts
        });
        return next();
      });
    });
    server.get('/api/media/campaigns/:campaign', function(req, res, next) {
      return db.Media.find({
        Campaign: req.params.campaign
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'campaign', req.params.campaign);
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/sites', function(req, res, next) {
      return db.Media.distinct('Site (DFA)', function(err, rslts) {
        var count;
        if (err) {
          return err;
        }
        rslts = _.without(rslts, '');
        count = rslts.length;
        res.send({
          'total sites': count,
          sites: rslts
        });
        return next();
      });
    });
    server.get('/api/media/sites/:site', function(req, res, next) {
      return db.Media.find({
        'Site (DFA)': req.params.site
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'site', req.params.site);
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/mobile/tablet/tactic', function(req, res, next) {
      return db.Media.distinct('Mobile/Tablet Tactic', function(err, rslts) {
        var count;
        if (err) {
          return err;
        }
        rslts = _.without(rslts, '');
        count = rslts.length;
        res.send({
          'total mobile/tablic tacitcs': count,
          'mobile/tablic tacitcs': rslts
        });
        return next();
      });
    });
    server.get('/api/media/mobile/tablet/tactic/:tacic', function(req, res, next) {
      return db.Media.find({
        'Mobile/Tablet Tactic': req.params.tactic
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'mobile/tablic tacitc', req.params.tactic);
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/tactics', function(req, res, next) {
      return db.Media.distinct('Placement Tactic', function(err, rslts) {
        var count;
        if (err) {
          return err;
        }
        rslts = _.without(rslts, '');
        count = rslts.length;
        res.send({
          'total tactics': count,
          'placement tactics': rslts
        });
        return next();
      });
    });
    server.get('/api/media/tactics/:tactic', function(req, res, next) {
      return db.Media.find({
        'Placement Tactic': req.params.tactic
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'tactic', req.params.tactic);
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/segments', function(req, res, next) {
      return db.Media.distinct('DMP Segment', function(err, rslts) {
        var count;
        if (err) {
          return err;
        }
        count = rslts.length;
        res.send({
          'total segments': count,
          'dmp segments': rslts
        });
        return next();
      });
    });
    server.get('/api/media/segments/:segment', function(req, res, next) {
      return db.Media.find({
        'DMP Segment': req.params.segment
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'segment', req.params.segment);
        res.send(rslts);
        return next();
      });
    });
    server.get('/api/media/months', function(req, res, next) {
      return db.Media.distinct('Date', function(err, rslts) {
        var count;
        if (err) {
          return err;
        }
        rslts = _.without(rslts, '');
        count = rslts.length;
        res.send({
          'total months': count,
          'months': rslts
        });
        return next();
      });
    });
    return server.get('/api/media/months/:date', function(req, res, next) {
      return db.Media.find({
        'Date': req.params.date
      }, function(err, rcrds) {
        var rslts;
        if (err) {
          return err;
        }
        rslts = rsltsObj(rcrds, 'month', req.params.date);
        res.send(rslts);
        return next();
      });
    });
  };

}).call(this);
