// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      "month": String,
      "year": Number,
      "days": Number,
      "holidays": [String]
    },
    collection: 'business_day',
    methods: {},
    validators: {},
    virtuals: {},
    hooks: {
      pre: {},
      post: {}
    }
  };

}).call(this);
