// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      'SegID': String,
      'VZ Marketing Universe': Number,
      'Epsilon SecureConnect': Number,
      'LiveRamp Audience Available for Syndication to AK': Number,
      'AK Audience': Number,
      'LiveRamp Audience': Number,
      'RocketFuel Audience': Number,
      'Reach': Number,
      'Frequency': Number,
      'Site Loop Qualify - Click': Number,
      'Site Loop Qualify - View': Number,
      'Site Subscribe/Sale': Date,
      'Site Audience': Date
    },
    collection: 'cookie',
    methods: {},
    validators: {},
    virtuals: {},
    hooks: {
      pre: {},
      post: {}
    }
  };

}).call(this);
