// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      'SegID': String,
      'Facebook': Number,
      'Yahoo': Number,
      'AOL': Number
    },
    collection: 'm2m',
    methods: {},
    validators: {},
    virtuals: {},
    hooks: {
      pre: {},
      post: {}
    }
  };

}).call(this);
