// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      'Description': String
    },
    'Business Rules': String({
      'Attribute Definition': String,
      'SegID': String,
      'Category': String
    }),
    collection: 'segment',
    methods: {},
    validators: {},
    virtuals: {},
    hooks: {
      pre: {},
      post: {}
    }
  };

}).call(this);
