// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      'Month': String,
      'Campaign': String,
      'Site (DFA)': String,
      'Placement': String,
      'Placement Group': String,
      'Placement Tactic': String,
      'DMP Segment': String,
      'Impressions': Number,
      'Clicks': Number,
      'CT TV LQS': Number,
      'VT TV LQS': Number,
      'Internet Orders': Number,
      'TV Orders': Number,
      'Internet AM CT Conversions': Number,
      'Internet AM CT Conversions': Number,
      'Internet NC CT Conversions': Number,
      'Internet NC TV Conversions': Number,
      'TV AM CT Conversions': Number,
      'TV AM VT Conversions': Number,
      'TV NC CT Conversions': Number,
      'TV NC VT Conversions': Number
    },
    methods: {},
    validators: {},
    virtuals: {},
    hooks: {
      pre: {},
      post: {}
    }
  };

}).call(this);
