// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      title: String,
      details: String,
      dueDate: Date,
      createdAt: {
        type: Date
      },
      _id: false,
      id: String,
      completed: {
        type: Boolean,
        "default": false
      }
    },
    methods: {},
    validators: {
      title: {
        fn: function(val) {
          return val.length > 3;
        },
        msg: 'Invalid title length.'
      }
    },
    virtuals: {},
    hooks: {
      pre: {
        save: function(next) {
          if (!this.id) {
            this.id = _str.slugify(this.title);
          }
          this.createdAt = Date.now();
          return next();
        }
      },
      post: {}
    },
    jsonOmit: ['_id']
  };

}).call(this);
