// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    model: {
      name: String,
      email: String,
      password: String,
      avatar: String,
      _id: false,
      id: String
    },
    methods: {},
    validators: {},
    virtuals: {},
    hooks: {
      pre: {},
      post: {}
    }
  };

}).call(this);
